### ISSUE TITLE
Question about former Linux Assembly guys

### ISSUE THREAD

**Issue by kkkrackpot** [lnoor/tinyrpc#2]
Hi Leo,

Is it correct that you're the very `lnoor` who is the current admin of Linux Assembly website (http://asm.sourceforge.net/) ?

In this case you might know how to contact Mr. Konstantin Boldyshev, the previous admin, or Mr. Nikolay Kurshev, his colleague?

Guys from mpv and mplayer project are looking for Mr. Kurshev, regarding code relicensing issues:  http://www.mplayerhq.hu/design7/news.html 
Sorry for abusing your github issue tracker this way, I did it because it looks like the fastest way to reach you. Feel free to delete it if you wish.

Sory if I'm not the only person bothering you with these question.

Regards,
Alex

**Comment by lnoor** [comment]
Hi Alex,
The only email address for Konstantin that I know is the one on the asm documentation page:
http://asm.sourceforge.net/resources.html#docs.

I am merely keeping the project alive but not much is happening and Konstantin has moved on to other projects a long time ago.

Sorry that I can't be of more help.
Leo

**Comment by kkkrackpot** [comment]
Thanks a lot for your reply!
And for the work you do to keep Linux Assembly site alive.

Regards,
Alex
